= How to Create a Landmask from Forcing Data
:author: David Mocko, Brendan McAndrew
:revdate: Feb 2020
:source-highlighter: highlight.js

:url-lis-docs: link:https://github.com/NASA-LIS/LISF/tree/master/docs[LISF Documentation]

:landmask-github: bmcandr/lis-landmask-guide
:landmask-clone-https: https://github.com/{landmask-github}
:landmask-clone-ssh: git@github.com:{landmask-github}

:scripts-dir: scripts
:netcdf-dir: {scripts-dir}/netcdf/
:binary-grads-dir: {scripts-dir}/binary/grads/
:binary-fortran-dir: {scripts-dir}/binary/fortran/

== Overview

LIS will halt if the forcing data is missing values for some land tiles in the selected landmask, typically along coastlines and/or for island points. An error message similar to the one below will be present in one of the log files:

[source, shell]
----
undefined value found for forcing variable tair in NoahMP401
 for tile            1 latitude =    30.23500     longitude =   -88.26501
 [ERR] endrun is being called
----

// TODO: add example figure of missing forcing within a domain

One solution to this error is to use a global surface forcing dataset in addition to your primary forcing with the "overlay" option (see the {url-lis-docs} for more). LIS will use the global forcing data wherever the primary forcing is not present. This is a simple solution, but it may result in longer run times because LIS has to read two different forcings.

The other solution, described here, is to generate a landmask from the forcing data itself.

:sectnums:

== Run LIS to Output Forcing Data

First, modify the model output attributes and LIS config files to output only a single forcing variable over the domain of interest.

=== Model Output Attributes File

["loweralpha"]
Copy your model output attributes file (e.g., _MODEL_OUTPUT_LIST.TBL.full_) to a new file (e.g., _MODEL_OUTPUT_LIST.TBL.forc_).

In the copy, disable all variable output except for a single forcing variable (such as air temperature):

[source, text]
----
#Forcings
Wind_f:       0  m/s     -    1 0 0 1  32 10      # Near surface wind (m/s)
Rainf_f:      0  kg/m2s  DN   1 0 0 1 162 1000    # Average rainfall rate
Snowf_f:      0  kg/m2s  DN   1 0 0 1 161 1000    # Average snowfall rate
CRainf_f:     0  kg/m2s  DN   1 0 0 1  63 1000    # Average convective rainfall rate
Tair_f:       1  K       -    1 0 0 1  11 10      # Near surface air temperature <1>
Qair_f:       0  kg/kg   -    1 0 0 1  51 1000    # Near surface specific humidity
Psurf_f:      0  Pa      -    1 0 0 1   1 10      # Surface pressure
SWdown_f:     0  W/m2    DN   1 0 0 1 204 10      # Surface incident shortwave radiation
LWdown_f:     0  W/m2    DN   1 0 0 1 205 10      # Surface incident longwave radiation
PARDR_f:      0  W/m2    DN   1 0 0 1 256 10      # Surface incident PAR direct
PARDF_f:      0  W/m2    DN   1 0 0 1 256 10      # Surface incident PAR diffuse
----
<1> `Tair_f` is the only forcing variable enabled for output as indicated by the `1` in the second column.

=== LIS Config File

Copy your existing LIS config file (e.g., _lis.config_) to a new file (e.g., _lis.config_forc_).

In the copy, update the path specified by `Model output attributes file:` to point to the modified model output attributes file:

[source, text]
----
Model output attributes file:           './MODEL_OUTPUT_LIST.TBL.forc'
----

Change the `Land surface model:` to `none` to select the template LSM:

[source, text]
----
Land surface model:         none
----

And add the following line:

[source, text]
----
TEMPLATE model timestep:    1hr
----

LIS only needs to run for a single, 1-hour timestep. Modify the ending date and time for the run so that it is 1 hour after the start time. For example:

[source]
----
Starting year:                          2000
Starting month:                            1
Starting day:                              1
Starting hour:                             0
Starting minute:                           0
Starting second:                           0
Ending year:                            2000
Ending month:                              1
Ending day:                                1
Ending hour:                               1
Ending minute:                             0
Ending second:                             0
----

Finally, change the output and log locations to avoid overwriting any existing files:

[source, text]
----
Output directory:           OUTPUT_FORCING/
Diagnostic output file:     OUTPUT_FORCING/logs/lislog
----

=== Run LIS

Run LIS using the _lis.config_forc_ file to generate an output file containing the air temperature forcing data. This output will be used to generate the mask file.

== Generate the Landmask File

For this step you will need a few domain parameters handy: the latitude and longitude of the lower left corner, the resolution, and the number of grid points in the x- and y-directions.

The coordinate and resolution values can be found in the LDT config file:

[source, text]
----
Run domain lower left lat:                 29.005
Run domain lower left lon:                -90.995
Run domain upper right lat:                30.595
Run domain upper right lon:               -88.005
Run domain resolution (dx):                0.01
Run domain resolution (dy):                0.01
----

The number of grid points in the x- and y-directions can be found in the header of a LIS log file produced by the previous run (e.g., _OUTPUT_FORCING/logs/lislog.0000_):

[source,shell]
----
[INFO] DOMAIN details:
[INFO] local domain:(          43          40 )
[INFO] local domain without halo:(          43          40 )
[INFO] running domain:(        300         160 ) <1>
----
<1> Grid points along the x- and y-dimensions, respectively.

---

// TODO update this section if this guide is included in the LISF repo
=== Clone this Repo

Clone this repository:

.HTTPS clone
[source, shell, subs="attributes"]
----
$ git clone {landmask-clone-https}
----

.SSH clone
[source, shell, subs="attributes"]
----
$ git clone {landmask-clone-ssh}
----

---

The source code and scripts referenced in the remainder of this step are located in the _{scripts-dir}_ directory of this repo.

Jump to the section that matches your LIS output file format:

* <<Sequential Binary Output (_.gs4r_ files), Binary>>
* <<NetCDF Output, NetCDF>>

=== Sequential Binary Output (_.gs4r_ files)

The landmask can be generated from binary output using either <<Fortran>> or <<GrADS>>.

==== Fortran

Copy the appropriate Fortran source file for your compiler from the _{binary-fortran-dir}_ into your LIS run directory.

Compile the _make_mask_binary_ executable:

.Intel Fortran compiler:
[source, shell]
----
$ ifort -o make_mask_binary make_mask_binary_IFORT.F90
----

.GFortran compiler:
[source, shell]
----
$ gfortran -o make_mask_binary make_mask_binary_GNU.F90
----

Run the executable:

[source, shell]
----
$ ./make_mask_binary OUTPUT_FORCING/SURFACEMODEL/200001/LIS_HIST_200001010100.d01.gs4r 300 160
----

The program takes three arguments:

[arabic]
. The relative path to the input file
. # grid points in the x-direction
. # grid points in the y-direction

The landmask will be written to a file named _forcing_mask.1gd4r_. Jump to <<step-3, Step 3>>.

==== GrADS

Copy _lis_output.ctl_ and _make_mask_binary.gs_ from the _{binary-grads-dir}_ directory into the LIS run directory.

Modify the `XDEF` and `YDEF` fields in _lis_output.ctl_ to match the LIS domain parameters:

._lis_output.ctl_
[source, text]
----
DSET        ^OUTPUT_FORCING/SURFACEMODEL/%y4%m2/LIS_HIST_%y4%m2%d2%h2%n2.d01.gs4r
TITLE        Forcing only output
UNDEF        -9999.0
OPTIONS      template
OPTIONS      sequential
OPTIONS      big_endian
XDEF               300 LINEAR        -90.995    0.01
YDEF               160 LINEAR         29.005    0.01
ZDEF                 1 LINEAR         0.0       1.0
TDEF                24 LINEAR  01Z01jan2000     1hr
VARS                 1
Tair_f_tavg          1 99 ** Near-surface air temperature [K]
ENDVARS
----

Run the _make_mask_binary.gs_ script:

[source, shell]
----
$ grads -lc "run make_mask_binary.gs"
----

Quit GrADS.

If successful, the landmask will be present in a file named _forcing_mask.1gd4r_. Quit GrADS and jump to <<step-3, Step 3>>.

=== NetCDF Output

[IMPORTANT]
====
GrADS is required to generate a landmask file from NetCDF output.
====

Copy _lis_output.xdf_ and _make_mask_netcdf.gs_ from the _{netcdf-dir}_ directory into the LIS run directory.

Modify the `XDEF` and `YDEF` fields in _lis_output.xdf_ to match the LIS domain parameters:

.lis_output.xdf
[source, text]
----
DSET        ^OUTPUT_FORCING/SURFACEMODEL/%y4%m2/LIS_HIST_%y4%m2%d2%h2%n2.d01.nc
TITLE        Forcing only output
DTYPE        netcdf
UNDEF        -9999.0
OPTIONS      template
XDEF east_west     300 LINEAR        -90.995     0.01
YDEF north_south   160 LINEAR         29.005     0.01
TDEF time           24 LINEAR  01Z01jan2000     1hr
----

Run the _make_mask_netcdf.gs_ script:

[source, shell]
----
$ grads -lc "run make_mask_netcdf.gs"
----

If successful, the landmask will be present in a file named _forcing_mask.1gd4r_. Quit GrADS and jump to <<step-3, Step 3>>.

=== Plot the Landmask (optional)

GrADS control files named _forcing_mask.ctl_ are provided for visualizing the landmask file. Copy the file to your LIS run directory and modify the `XDEF` and `YDEF` fields as above. Use GrADS to view the file:

[source, shell]
----
$ grads -lc "open forcing_mask.ctl"
ga-> set gxout grfill
ga-> d mask
----

// TODO: add figure of landmask

[[step-3]]
== Generate a LIS Input File based on the Landmask

Add the following lines to your original LDT configuration file to read in the landmask file generated in the previous step, modifying the regional mask `lat`, `lon`, and `resolution` fields to match the LIS domain parameters:

[source, text]
----
Regional mask file:                     ./forcing_mask.1gd4r
Regional mask data source:              file
Clip landmask with regional mask:       .true.
Regional mask spatial transform:        none
Regional mask map projection:           latlon
Regional mask lower left lat:           29.005
Regional mask lower left lon:          -90.995
Regional mask upper right lat:          30.595
Regional mask upper right lon:         -88.005
Regional mask resolution (dx):          0.01
Regional mask resolution (dy):          0.01
----

Run LDT with the modified config file to generate a LIS parameter file based on the landmask.

:sectnums!:

== Conclusion

LIS should now run without error using the selected forcing data.
